### ISSUE TITLE
Get low macro-F1 run quick start on K40

### ISSUE THREAD

**Issue by bluemandora** [DeepGraphLearning/graphvite#10]
I run the quick start example using following command: 
`graphvite baseline quick start`
Here is the output, loss always zero and macro-F1@20%: 0.0266747.
Do I need tune some params to get your reported result?

```
running baseline: quick_start.yaml
loading graph from /home/work/.graphvite/dataset/blogcatalog/blogcatalog_train.txt
0.00018387%
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Graph<uint32>
------------------ Graph -------------------
#vertex: 10312, #edge: 333983
as undirected: yes, normalization: no
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[time] GraphApplication.load: 0.166404 s
[time] GraphApplication.build: 0.927183 s
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
GraphSolver<128, float32, uint32>
----------------- Resource -----------------
#worker: 1, #sampler: 7, #partition: 1
tied weights: no, episode size: 500
gpu memory limit: 11.1 GiB
gpu memory cost: 51.5 MiB
----------------- Sampling -----------------
augmentation step: 2, shuffle base: 2
random walk length: 40
random walk batch size: 100
#negative: 1, negative sample exponent: 0.75
----------------- Training -----------------
model: LINE
optimizer: SGD
learning rate: 0.025, lr schedule: linear
weight decay: 0.005
#epoch: 2000, batch size: 100000
resume: no
positive reuse: 1, negative weight: 5
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Batch id: 0 / 6679
loss = 0
Batch id: 1000 / 6679
loss = 0
Batch id: 2000 / 6679
loss = 0
Batch id: 3000 / 6679
loss = 0
Batch id: 4000 / 6679
loss = 0
Batch id: 5000 / 6679
loss = 0
Batch id: 6000 / 6679
loss = 0
[time] GraphApplication.train: 9.46801 s
evaluate on node classification
effective labels: 14476 / 14476
macro-F1@20%: 0.0266747
micro-F1@20%: 0.168389
[time] GraphApplication.evaluate: 17.9303 s
save embeddings and name mappings to `line_blogcatalog.pkl`
[time] GraphApplication.save: 0.0503972 s
```

**Comment by KiddoZhu** [comment]
It seems that the GPU code doesn't work. Which GPU are you using?

**Comment by bluemandora** [comment]
@KiddoZhu Tesla K40m
```
Tue Aug 13 11:10:27 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.74       Driver Version: 418.74       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K40m          On   | 00000000:03:00.0 Off |                    0 |
| N/A   30C    P8    20W / 235W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K40m          On   | 00000000:04:00.0 Off |                    0 |
| N/A   29C    P8    20W / 235W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K40m          On   | 00000000:83:00.0 Off |                    0 |
| N/A   28C    P8    20W / 235W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K40m          On   | 00000000:84:00.0 Off |                    0 |
| N/A   31C    P8    19W / 235W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by KiddoZhu** [comment]
Sorry we didn't take Kepler series into consideration. The conda version is compiled against Maxwell series and later to reduce the size of binary.

You need to compile the code on your hardware. It should automatically detect the architecture, printing something like `Autodetected CUDA architecture(s): 3.5` during `cmake`. I think it should be compatible with Kepler series, although not verified.

**Comment by bluemandora** [comment]
I met some error while compile the code.
```
-- The CXX compiler identification is GNU 7.3.0
-- The CUDA compiler identification is unknown
-- Check for working CXX compiler: /home/work/anaconda2/envs/graphvite/bin/c++
-- Check for working CXX compiler: /home/work/anaconda2/envs/graphvite/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /home/work/fuyan01/env/cuda-9.2/bin/nvcc
-- Check for working CUDA compiler: /home/work/fuyan01/env/cuda-9.2/bin/nvcc -- broken
CMake Error at /data/anaconda2/envs/graphvite/share/cmake-3.15/Modules/CMakeTestCUDACompiler.cmake:46 (message):
  The CUDA compiler

    "/home/work/fuyan01/env/cuda-9.2/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/work/fuyan01/graphvite/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake cmTC_607a2/fast && /usr/bin/gmake -f CMakeFiles/cmTC_607a2.dir/build.make CMakeFiles/cmTC_607a2.dir/build
    gmake[1]: Entering directory `/data/fuyan01/graphvite/build/CMakeFiles/CMakeTmp'
    Building CUDA object CMakeFiles/cmTC_607a2.dir/main.cu.o
    /home/work/fuyan01/env/cuda-9.2/bin/nvcc     -x cu -c /home/work/fuyan01/graphvite/build/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_607a2.dir/main.cu.o
    Linking CUDA executable cmTC_607a2
    /data/anaconda2/envs/graphvite/bin/cmake -E cmake_link_script CMakeFiles/cmTC_607a2.dir/link.txt --verbose=1
    "" -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections  CMakeFiles/cmTC_607a2.dir/main.cu.o -o cmTC_607a2 
    Error running link command: No such file or directory
    gmake[1]: *** [cmTC_607a2] Error 2
    gmake[1]: Leaving directory `/data/fuyan01/graphvite/build/CMakeFiles/CMakeTmp'
    gmake: *** [cmTC_607a2/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)


-- Configuring incomplete, errors occurred!
See also "/home/work/fuyan01/graphvite/build/CMakeFiles/CMakeOutput.log".
See also "/home/work/fuyan01/graphvite/build/CMakeFiles/CMakeError.log".
```
Here is CMakeError.log:
```
Compiling the CUDA compiler identification source file "CMakeCUDACompilerId.cu" failed.
Compiler: /home/work/fuyan01/env/cuda-9.2/bin/nvcc 
Build flags: 
Id flags:  -v;--keep;--keep-dir;tmp

The output was:
1
#$ _SPACE_= 
#$ _CUDART_=cudart
#$ _HERE_=/home/work/fuyan01/env/cuda-9.2/bin
#$ _THERE_=/home/work/fuyan01/env/cuda-9.2/bin
#$ _TARGET_SIZE_=
#$ _TARGET_DIR_=
#$ _TARGET_SIZE_=64
#$ TOP=/home/work/fuyan01/env/cuda-9.2/bin/..
#$ NVVMIR_LIBRARY_DIR=/home/work/fuyan01/env/cuda-9.2/bin/../nvvm/libdevice
#$ LD_LIBRARY_PATH=/home/work/fuyan01/env/cuda-9.2/bin/../lib:$CUDA_HOME/lib64:$LD_LIBRARY_PATH
#$ PATH=/home/work/fuyan01/env/cuda-9.2/bin/../nvvm/bin:/home/work/fuyan01/env/cuda-9.2/bin:/home/work/anaconda2/envs/graphvite/bin:/home/work/anaconda2/condabin:/home/work/.jumbo/bin:/home/work/opt/openmpi/bin:/home/work/anaconda2/bin:/home/work/.jumbo/bin:/home/work/opt/openmpi/bin:/home/work/anaconda2/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/work/.local/bin:/home/work/bin
#$ INCLUDES="-I/home/work/fuyan01/env/cuda-9.2/bin/..//include"  
#$ LIBRARIES=  "-L/home/work/fuyan01/env/cuda-9.2/bin/..//lib64/stubs" "-L/home/work/fuyan01/env/cuda-9.2/bin/..//lib64"
#$ CUDAFE_FLAGS=
#$ PTXAS_FLAGS=
#$ rm tmp/a_dlink.reg.c
#$ gcc -D__CUDA_ARCH__=300 -E -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__  "-I/home/work/fuyan01/env/cuda-9.2/bin/..//include"   -D"__CUDACC_VER_BUILD__=148" -D"__CUDACC_VER_MINOR__=2" -D"__CUDACC_VER_MAJOR__=9" -include "cuda_runtime.h" -m64 "CMakeCUDACompilerId.cu" > "tmp/CMakeCUDACompilerId.cpp1.ii" 
#$ cicc --gnu_version=40805 --allow_managed   -arch compute_30 -m64 -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name "CMakeCUDACompilerId.fatbin.c" -tused -nvvmir-library "/home/work/fuyan01/env/cuda-9.2/bin/../nvvm/libdevice/libdevice.10.bc" --gen_module_id_file --module_id_file_name "tmp/CMakeCUDACompilerId.module_id" --orig_src_file_name "CMakeCUDACompilerId.cu" --gen_c_file_name "tmp/CMakeCUDACompilerId.cudafe1.c" --stub_file_name "tmp/CMakeCUDACompilerId.cudafe1.stub.c" --gen_device_file_name "tmp/CMakeCUDACompilerId.cudafe1.gpu"  "tmp/CMakeCUDACompilerId.cpp1.ii" -o "tmp/CMakeCUDACompilerId.ptx"
#$ ptxas -arch=sm_30 -m64  "tmp/CMakeCUDACompilerId.ptx"  -o "tmp/CMakeCUDACompilerId.sm_30.cubin" 
#$ fatbinary --create="tmp/CMakeCUDACompilerId.fatbin" -64 "--image=profile=sm_30,file=tmp/CMakeCUDACompilerId.sm_30.cubin" "--image=profile=compute_30,file=tmp/CMakeCUDACompilerId.ptx" --embedded-fatbin="tmp/CMakeCUDACompilerId.fatbin.c" --cuda
#$ gcc -E -x c++ -D__CUDACC__ -D__NVCC__  "-I/home/work/fuyan01/env/cuda-9.2/bin/..//include"   -D"__CUDACC_VER_BUILD__=148" -D"__CUDACC_VER_MINOR__=2" -D"__CUDACC_VER_MAJOR__=9" -include "cuda_runtime.h" -m64 "CMakeCUDACompilerId.cu" > "tmp/CMakeCUDACompilerId.cpp4.ii" 
#$ cudafe++ --gnu_version=40805 --allow_managed  --m64 --parse_templates --gen_c_file_name "tmp/CMakeCUDACompilerId.cudafe1.cpp" --stub_file_name "CMakeCUDACompilerId.cudafe1.stub.c" --module_id_file_name "tmp/CMakeCUDACompilerId.module_id" "tmp/CMakeCUDACompilerId.cpp4.ii" 
#$ gcc -D__CUDA_ARCH__=300 -c -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS "-I/home/work/fuyan01/env/cuda-9.2/bin/..//include"   -m64 -o "tmp/CMakeCUDACompilerId.o" "tmp/CMakeCUDACompilerId.cudafe1.cpp" 
#$ nvlink --arch=sm_30 --register-link-binaries="tmp/a_dlink.reg.c"  -m64   "-L/home/work/fuyan01/env/cuda-9.2/bin/..//lib64/stubs" "-L/home/work/fuyan01/env/cuda-9.2/bin/..//lib64" -cpu-arch=X86_64 "tmp/CMakeCUDACompilerId.o"  -o "tmp/a_dlink.sm_30.cubin"
#$ fatbinary --create="tmp/a_dlink.fatbin" -64 -link "--image=profile=sm_30,file=tmp/a_dlink.sm_30.cubin" --embedded-fatbin="tmp/a_dlink.fatbin.c" 
#$ gcc -c -x c++ -DFATBINFILE="\"tmp/a_dlink.fatbin.c\"" -DREGISTERLINKBINARYFILE="\"tmp/a_dlink.reg.c\"" -I. -D__NV_EXTRA_INITIALIZATION= -D__NV_EXTRA_FINALIZATION=  "-I/home/work/fuyan01/env/cuda-9.2/bin/..//include"   -D"__CUDACC_VER_BUILD__=148" -D"__CUDACC_VER_MINOR__=2" -D"__CUDACC_VER_MAJOR__=9" -m64 -o "tmp/a_dlink.o" "/home/work/fuyan01/env/cuda-9.2/bin/crt/link.stub" 
#$ g++ -m64 -o "a.out" -Wl,--start-group "tmp/a_dlink.o" "tmp/CMakeCUDACompilerId.o"   "-L/home/work/fuyan01/env/cuda-9.2/bin/..//lib64/stubs" "-L/home/work/fuyan01/env/cuda-9.2/bin/..//lib64" -lcudadevrt  -lcudart_static  -lrt -lpthread  -ldl  -Wl,--end-group 
/data/anaconda2/envs/graphvite/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: tmp/CMakeCUDACompilerId.o: relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/data/anaconda2/envs/graphvite/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
# --error 0x1 --


Determining if the CUDA compiler works failed with the following output:
Change Dir: /home/work/fuyan01/graphvite/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_607a2/fast && /usr/bin/gmake -f CMakeFiles/cmTC_607a2.dir/build.make CMakeFiles/cmTC_607a2.dir/build
gmake[1]: Entering directory `/data/fuyan01/graphvite/build/CMakeFiles/CMakeTmp'
Building CUDA object CMakeFiles/cmTC_607a2.dir/main.cu.o
/home/work/fuyan01/env/cuda-9.2/bin/nvcc     -x cu -c /home/work/fuyan01/graphvite/build/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_607a2.dir/main.cu.o
Linking CUDA executable cmTC_607a2
/data/anaconda2/envs/graphvite/bin/cmake -E cmake_link_script CMakeFiles/cmTC_607a2.dir/link.txt --verbose=1
"" -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections  CMakeFiles/cmTC_607a2.dir/main.cu.o -o cmTC_607a2 
Error running link command: No such file or directory
gmake[1]: *** [cmTC_607a2] Error 2
gmake[1]: Leaving directory `/data/fuyan01/graphvite/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_607a2/fast] Error 2
```
Do you have any idea of what's going on?

**Comment by KiddoZhu** [comment]
Maybe `nvcc` called some broken compiling tools in conda. I am not sure about the exact reason, but a work around is to use `conda uninstall cxx-compiler` and try again. Note you need to remove the `CMakeCache.txt`.

**Comment by bluemandora** [comment]
I got `cmake ..` and `make` work. But when I execute `python setup.py install`, other issue occured:
```
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    from graphvite import __version__, lib_path, lib_file
  File "/data/fuyan01/graphvite/python/graphvite/__init__.py", line 36, in <module>
    lib = imp.load_dynamic("libgraphvite", lib_file)
  File "/home/work/anaconda2/envs/graphvite/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /data/fuyan01/graphvite/python/graphvite/../../build/lib/libgraphvite.so: undefined symbol: _ZN3fLS13FLAGS_log_dirE
```
Here is CMAKE output, nothing seems to be wrong.
```
-- The CUDA compiler identification is NVIDIA 9.2.148
-- Check for working CUDA compiler: /home/work/fuyan01/env/cuda-9.2/bin/nvcc
-- Check for working CUDA compiler: /home/work/fuyan01/env/cuda-9.2/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /data/fuyan01/env/cuda-9.2/ (found version "9.2") 
-- Found Glog: /usr/include  
-- Found glog    (include: /usr/include, library: /usr/lib64/libglog.so)
-- Found GFlags: /data/anaconda2/envs/graphvite/include  
-- Found gflags  (include: /data/anaconda2/envs/graphvite/include, library: /data/anaconda2/envs/graphvite/lib/libgflags.so)
-- Found PythonInterp: /home/work/anaconda2/envs/graphvite/bin/python (found version "3.7.3") 
-- Found PythonLibs: /home/work/anaconda2/envs/graphvite/lib/libpython3.7m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Failed
-- Performing Test HAS_CPP11_FLAG
-- Performing Test HAS_CPP11_FLAG - Success
-- Autodetected CUDA architecture(s):  3.5
-- Configuring done
-- Generating done
-- Build files have been written to: /home/work/fuyan01/graphvite/build
```
```
$ ldd -r libgraphvite.so 
        linux-vdso.so.1 =>  (0x00007ffdf3b38000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fdf6fd47000)
        libcurand.so.9.2 => /data/fuyan01/env/cuda-9.2/lib64/libcurand.so.9.2 (0x00007fdf6be09000)
        libglog.so.0 => /lib64/libglog.so.0 (0x00007fdf6bbd9000)
        libfaiss.so => /data/fuyan01/graphvite/build/lib/./libfaiss.so (0x00007fdf6758d000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fdf67385000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fdf67181000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fdf66e7a000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fdf66b78000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fdf66962000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fdf66595000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdf7073c000)
        libgflags.so.2.1 => /lib64/libgflags.so.2.1 (0x00007fdf66374000)
        libopenblas.so.0 => /opt/OpenBLAS/lib/libopenblas.so.0 (0x00007fdf65447000)
        liblapack.so.3 => /lib64/liblapack.so.3 (0x00007fdf64cea000)
        libcudart.so.9.2 => /data/fuyan01/env/cuda-9.2/lib64/libcudart.so.9.2 (0x00007fdf64a80000)
        libcublas.so.9.2 => /data/fuyan01/env/cuda-9.2/lib64/libcublas.so.9.2 (0x00007fdf61032000)
        libgomp.so.1 => /lib64/libgomp.so.1 (0x00007fdf60e0c000)
        libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00007fdf60aea000)
        libblas.so.3 => /lib64/libblas.so.3 (0x00007fdf60891000)
        libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007fdf60655000)
undefined symbol: PyInstanceMethod_Type (./libgraphvite.so)
undefined symbol: PyExc_ValueError      (./libgraphvite.so)
undefined symbol: _Py_TrueStruct        (./libgraphvite.so)
undefined symbol: PyExc_IndexError      (./libgraphvite.so)
undefined symbol: PyCapsule_Type        (./libgraphvite.so)
undefined symbol: PyModule_Type (./libgraphvite.so)
undefined symbol: _Py_NoneStruct        (./libgraphvite.so)
undefined symbol: PyExc_MemoryError     (./libgraphvite.so)
undefined symbol: PyType_Type   (./libgraphvite.so)
undefined symbol: PyCFunction_Type      (./libgraphvite.so)
undefined symbol: PyProperty_Type       (./libgraphvite.so)
undefined symbol: PyExc_BufferError     (./libgraphvite.so)
undefined symbol: PyExc_RuntimeError    (./libgraphvite.so)
undefined symbol: _Py_NotImplementedStruct      (./libgraphvite.so)
undefined symbol: PyBaseObject_Type     (./libgraphvite.so)
undefined symbol: PyExc_TypeError       (./libgraphvite.so)
undefined symbol: PyMethod_Type (./libgraphvite.so)
undefined symbol: _Py_FalseStruct       (./libgraphvite.so)
undefined symbol: PyExc_FutureWarning   (./libgraphvite.so)
undefined symbol: PyDict_Type   (./libgraphvite.so)
undefined symbol: PyFloat_Type  (./libgraphvite.so)
undefined symbol: PyExc_SystemError     (./libgraphvite.so)
undefined symbol: PyExc_ImportError     (./libgraphvite.so)
undefined symbol: PyTuple_SetItem       (./libgraphvite.so)
undefined symbol: PyObject_Repr (./libgraphvite.so)
undefined symbol: PyLong_AsLong (./libgraphvite.so)
undefined symbol: PyLong_FromSsize_t    (./libgraphvite.so)
undefined symbol: PyObject_GetAttr      (./libgraphvite.so)
undefined symbol: PyDict_GetItemString  (./libgraphvite.so)
undefined symbol: PyImport_AddModule    (./libgraphvite.so)
undefined symbol: PyObject_Call (./libgraphvite.so)
undefined symbol: PyNumber_And  (./libgraphvite.so)
undefined symbol: PyErr_NormalizeException      (./libgraphvite.so)
undefined symbol: PyInstanceMethod_New  (./libgraphvite.so)
undefined symbol: PyEval_AcquireThread  (./libgraphvite.so)
undefined symbol: PyObject_Str  (./libgraphvite.so)
undefined symbol: PyThreadState_DeleteCurrent   (./libgraphvite.so)
undefined symbol: PyGILState_GetThisThreadState (./libgraphvite.so)
undefined symbol: PyObject_GetAttrString        (./libgraphvite.so)
undefined symbol: PyMem_Free    (./libgraphvite.so)
undefined symbol: PyErr_Restore (./libgraphvite.so)
undefined symbol: PyType_IsSubtype      (./libgraphvite.so)
undefined symbol: PyModule_AddObject    (./libgraphvite.so)
undefined symbol: PyErr_WarnEx  (./libgraphvite.so)
undefined symbol: PyTuple_New   (./libgraphvite.so)
undefined symbol: PyObject_SetAttr      (./libgraphvite.so)
undefined symbol: PyObject_IsInstance   (./libgraphvite.so)
undefined symbol: PyEval_RestoreThread  (./libgraphvite.so)
undefined symbol: PyException_SetTraceback      (./libgraphvite.so)
undefined symbol: PyNumber_Float        (./libgraphvite.so)
undefined symbol: PyUnicode_FromFormat  (./libgraphvite.so)
undefined symbol: PyList_Append (./libgraphvite.so)
undefined symbol: PyDict_Contains       (./libgraphvite.so)
undefined symbol: PyDict_Next   (./libgraphvite.so)
undefined symbol: PyList_Size   (./libgraphvite.so)
undefined symbol: PyTuple_Size  (./libgraphvite.so)
undefined symbol: PyNumber_Long (./libgraphvite.so)
undefined symbol: PyBuffer_Release      (./libgraphvite.so)
undefined symbol: PyObject_GetIter      (./libgraphvite.so)
undefined symbol: PyErr_Format  (./libgraphvite.so)
undefined symbol: PyObject_CallObject   (./libgraphvite.so)
undefined symbol: PyFloat_FromDouble    (./libgraphvite.so)
undefined symbol: PyFloat_AsDouble      (./libgraphvite.so)
undefined symbol: PyUnicode_DecodeUTF8  (./libgraphvite.so)
undefined symbol: PyErr_ExceptionMatches        (./libgraphvite.so)
undefined symbol: PyCFunction_NewEx     (./libgraphvite.so)
undefined symbol: PyList_New    (./libgraphvite.so)
undefined symbol: PyImport_ImportModule (./libgraphvite.so)
undefined symbol: PyNumber_Check        (./libgraphvite.so)
undefined symbol: _PyObject_GetDictPtr  (./libgraphvite.so)
undefined symbol: PyUnicode_FromString  (./libgraphvite.so)
undefined symbol: Py_GetVersion (./libgraphvite.so)
undefined symbol: PyCapsule_SetContext  (./libgraphvite.so)
undefined symbol: PyFrame_GetLineNumber (./libgraphvite.so)
undefined symbol: PyThread_tss_get      (./libgraphvite.so)
undefined symbol: PyBytes_Size  (./libgraphvite.so)
undefined symbol: PySequence_Check      (./libgraphvite.so)
undefined symbol: PyList_GetItem        (./libgraphvite.so)
undefined symbol: PyErr_Clear   (./libgraphvite.so)
undefined symbol: PyObject_HasAttrString        (./libgraphvite.so)
undefined symbol: PyWeakref_NewRef      (./libgraphvite.so)
undefined symbol: PyModule_GetName      (./libgraphvite.so)
undefined symbol: PyDict_New    (./libgraphvite.so)
undefined symbol: PyErr_SetString       (./libgraphvite.so)
undefined symbol: PyEval_InitThreads    (./libgraphvite.so)
undefined symbol: PyCapsule_GetContext  (./libgraphvite.so)
undefined symbol: PyThreadState_Get     (./libgraphvite.so)
undefined symbol: PyObject_SetItem      (./libgraphvite.so)
undefined symbol: PyCapsule_New (./libgraphvite.so)
undefined symbol: PyMem_Calloc  (./libgraphvite.so)
undefined symbol: PyObject_SetAttrString        (./libgraphvite.so)
undefined symbol: PyCapsule_GetPointer  (./libgraphvite.so)
undefined symbol: PyNumber_Xor  (./libgraphvite.so)
undefined symbol: PyThread_tss_alloc    (./libgraphvite.so)
undefined symbol: PyBytes_AsString      (./libgraphvite.so)
undefined symbol: PyThread_tss_set      (./libgraphvite.so)
undefined symbol: PyObject_GetItem      (./libgraphvite.so)
undefined symbol: PyType_Ready  (./libgraphvite.so)
undefined symbol: PyEval_SaveThread     (./libgraphvite.so)
undefined symbol: PySequence_GetItem    (./libgraphvite.so)
undefined symbol: PyObject_ClearWeakRefs        (./libgraphvite.so)
undefined symbol: PySequence_Size       (./libgraphvite.so)
undefined symbol: PyLong_FromLong       (./libgraphvite.so)
undefined symbol: PyEval_GetBuiltins    (./libgraphvite.so)
undefined symbol: PyObject_RichCompareBool      (./libgraphvite.so)
undefined symbol: PyNumber_Or   (./libgraphvite.so)
undefined symbol: PyModule_Create2      (./libgraphvite.so)
undefined symbol: PyThread_tss_create   (./libgraphvite.so)
undefined symbol: PyLong_AsUnsignedLong (./libgraphvite.so)
undefined symbol: PyLong_FromSize_t     (./libgraphvite.so)
undefined symbol: PyUnicode_AsEncodedString     (./libgraphvite.so)
undefined symbol: PyErr_Occurred        (./libgraphvite.so)
undefined symbol: PyDict_Copy   (./libgraphvite.so)
undefined symbol: PyErr_Fetch   (./libgraphvite.so)
undefined symbol: PyThreadState_New     (./libgraphvite.so)
undefined symbol: _PyThreadState_UncheckedGet   (./libgraphvite.so)
undefined symbol: _PyType_Lookup        (./libgraphvite.so)
undefined symbol: PyObject_CallFunctionObjArgs  (./libgraphvite.so)
undefined symbol: PyDict_Size   (./libgraphvite.so)
undefined symbol: PyIter_Next   (./libgraphvite.so)
undefined symbol: PyCallable_Check      (./libgraphvite.so)
undefined symbol: PySequence_Tuple      (./libgraphvite.so)
undefined symbol: PyThreadState_Clear   (./libgraphvite.so)
undefined symbol: PyDict_DelItemString  (./libgraphvite.so)
undefined symbol: PyObject_Malloc       (./libgraphvite.so)
undefined symbol: PyCapsule_GetName     (./libgraphvite.so)
undefined symbol: PyTuple_GetItem       (./libgraphvite.so)
undefined symbol: PyUnicode_AsUTF8String        (./libgraphvite.so)
undefined symbol: PyUnicode_FromStringAndSize   (./libgraphvite.so)
undefined symbol: PyBytes_AsStringAndSize       (./libgraphvite.so)
```

**Comment by KiddoZhu** [comment]
Sorry but I'm also very confused at this output.

It seems that your Python interpreters are the same for compilation and install, but there are still undefined symbols for `Py....`. And I noticed that `gflags` are different in cmake and ldd outputs. Could you check all the paths related to `gflags` in your `build/CMakeCache.txt`? You may need to modify some of the paths, and run `cmake` and `make` again.

**Comment by bluemandora** [comment]
Set LD_PRELOAD solved the problem. Loss is as expected now.

**Comment by bangdo172** [comment]
> Set LD_PRELOAD solved the problem. Loss is as expected now.

can you explain how you set LD_PRELOAD?

**Comment by bluemandora** [comment]
> > Set LD_PRELOAD solved the problem. Loss is as expected now.
> 
> can you explain how you set LD_PRELOAD?

export LD_PRELOAD=/where/is/libgflags.so:/where/is/libglog.so
