### ISSUE TITLE
When running with quick_start.yaml with own dataset getting the following error

### ISSUE THREAD

**Issue by Shraban123** [DeepGraphLearning/graphvite#112]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/opt/conda/lib/python3.7/site-packages/graphvite-0.1.0-py3.7.egg/graphvite/application/application.py", line 411, in linear_classification
    loss.backward()
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/bin/graphvite", line 11, in <module>
    load_entry_point('graphvite==0.1.0', 'console_scripts', 'graphvite')()
  File "/opt/conda/lib/python3.7/site-packages/graphvite-0.1.0-py3.7.egg/graphvite/cmd.py", line 212, in main
    command[args.command](args)
  File "/opt/conda/lib/python3.7/site-packages/graphvite-0.1.0-py3.7.egg/graphvite/cmd.py", line 110, in run_main
    app.evaluate(**cfg.evaluate)
  File "/opt/conda/lib/python3.7/site-packages/graphvite-0.1.0-py3.7.egg/graphvite/util.py", line 95, in wrapper
    result = function(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/graphvite-0.1.0-py3.7.egg/graphvite/application/application.py", line 101, in evaluate
    result = getattr(self, func_name)(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/graphvite-0.1.0-py3.7.egg/graphvite/application/application.py", line 261, in node_classification
    results = self.gpu_map(linear_classification, settings)
  File "/opt/conda/lib/python3.7/site-packages/graphvite-0.1.0-py3.7.egg/graphvite/application/application.py", line 159, in gpu_map
    results = pool.map(func, settings, chunksize=1)
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

**Comment by Shraban123** [comment]
application:
  graph

resource:
  gpus: []
  cpu_per_gpu: 2
  dim: 128

format:
  delimiters: " "
  comment: "#"

graph:
  #file_name: '/home/shraban/Paper2/LINE/cora_edge_list.txt'
  file_name: '/home/shraban/Paper2/LINE/demo_list.txt'
  as_undirected: true

build:
  optimizer:
    type: SGD
    lr: 0.025
    weight_decay: 0.005
  num_partition: auto
  num_negative: 1
  batch_size: 7 # must be greater than numbe of nodes
  episode_size: 2

train:
  model: LINE
  num_epoch: 10
  negative_weight: 2
  augmentation_step: 2
  random_walk_length: 2
  random_walk_batch_size: 2
  log_frequency: 10

evaluate:
    task: node classification
    #file_name: '/home/shraban/Paper2/LINE/cora_labels.txt'
    file_name: '/home/shraban/Paper2/LINE/demo_labels.txt'
    portions: [1]
    times: 1

save:
  file_name: line_cora.pkl
