### ISSUE TITLE
Publish conda recipes to conda-forge?

### ISSUE THREAD

**Issue by h-vetinari** [DeepGraphLearning/graphvite#2]
Hey, I was wondering if you have considered publishing the conda recipes to [conda-forge](https://github.com/conda-forge/staged-recipes)? That way, people could install graphvite directly from conda-forge (and wouldn't run into problems like #1, because only one channel is needed).

Adding other channels is sometimes very hard (imagine a firewall that only allows main and conda-forge), and can also complicate package resolution (especially with `--strict-channel-priority`, which will become the default soon-ish).

**Comment by KiddoZhu** [comment]
Good idea! We will work on that.

**Comment by h-vetinari** [comment]
> @KiddoZhu: Good idea! We will work on that.

If you want, I can help with that.

**Comment by zjduan** [comment]
@h-vetinari Hi! I am working on publishing conda recipes to conda-forge. How can I add gpu support? More specifically, I can not pass the check on conda-forge, and here is the error information:

```
-- The CXX compiler identification is GNU 5.4.0
-- The CUDA compiler identification is unknown
-- Check for working CXX compiler: $BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-c++
-- Check for working CXX compiler: $BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:6 (project):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "$SRC_DIR/build/CMakeFiles/CMakeOutput.log".
See also "$SRC_DIR/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/home/conda/.ci_support/build_all.py", line 131, in <module>
    build_all(args.recipes_dir, args.arch)
  File "/home/conda/.ci_support/build_all.py", line 68, in build_all
    build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
  File "/home/conda/.ci_support/build_all.py", line 121, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2343, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1491, in build
    cwd=src_dir, stats=build_stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 397, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 377, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/conda/feedstock_root/build_artifacts/graphvite_1565975956673/work/conda_build.sh']' returned non-zero exit status 1.
##[error]Bash exited with code '1'.
##[section]Finishing: Run docker build
```

It seems that there is no cuda in the VM. How to deal with that?

**Comment by h-vetinari** [comment]
@zjduan 
Hey, sorry for the late reply.

Can you post the content of your `meta.yaml`? To have the compiler (IIUC), you can require [`cudatoolkit-dev`](https://github.com/conda-forge/cudatoolkit-dev-feedstock).

**Comment by zjduan** [comment]
OK, this is the content of my `meta.yaml`
```
{% set build_number = "0" %}

package:
  name: graphvite
  version: 0.1.0

source:
  url: https://github.com/DeepGraphLearning/graphvite/archive/master.zip
  sha256: 3dd505d939204e41f762a18d51b3719e327a5fe461bce0dd0e8ce07cab37272b

build:
  skip: true  # [not linux]
  number: {{ build_number }}
  string: py{{ python|replace(".", "") }}cuda{{ cudatoolkit|replace(".", "") }}_{{ build_number }}

requirements:
  build:
    # cmake
    - cmake >=3.12
    - {{ compiler("cxx") }}
    - glog
    - gflags
    - cudatoolkit {{ cudatoolkit }}
    - python {{ python }}
    - pybind11
  host:
    # make
    - glog
    - gflags
    - cudatoolkit {{ cudatoolkit }}
    - python {{ python }}
    - pybind11
    - mkl >=2018
    # setup
    - numpy {{ numpy }}
    - pyyaml
    - easydict
    - six
  run:
    - glog
    - gflags
    - cudatoolkit
    - python {{ python }}
    - mkl >=2018
    - numpy >=1.11
    - pyyaml
    - easydict
    - six
    - future
    - imageio
    - scipy
    - matplotlib
    - pytorch
    - torchvision
    - nltk

test:
  imports:
    - graphvite

about:
  home: https://graphvite.io
  license: Apache-2.0
  license_file: LICENSE
  summary: 'A general and high-performance graph embedding system for various applications'

extra:
  recipe-maintainers:
    - KiddoZhu
    - zjduan
```
And this is my content of `conda_build_config.yaml`
```
cxx_compiler_version:
  - 5.4

python:
  - 2.7
  - 3.6
  - 3.7

numpy:
  - 1.11

cudatoolkit:
  - 9.2
  - 10.0

pin_run_as_build:
  cudatoolkit:
    max_pin: x.x

```

**Comment by h-vetinari** [comment]
Can you try changing the dependencies for build/host from `cudatoolkit` to `cudatoolkit-dev`? I'm not sure about the runtime dependency - do you still need the compiler then?

**Comment by zjduan** [comment]
@h-vetinari  
Hello! I have tried to use `cudatoolkit-dev` and I get the following error information:
```
  File "/home/zjduan/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/forge_gv/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "/home/zjduan/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/forge_gv/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "/home/zjduan/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/forge_gv/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/zjduan/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/forge_gv/lib/python3.7/site-packages/conda_build/build.py", line 2343, in build_tree
    notest=notest,
  File "/home/zjduan/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/forge_gv/lib/python3.7/site-packages/conda_build/build.py", line 1407, in build
    create_build_envs(top_level_pkg, notest)
  File "/home/zjduan/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/forge_gv/lib/python3.7/site-packages/conda_build/build.py", line 1247, in create_build_envs
    is_conda=m.name() == 'conda')
  File "/home/zjduan/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/forge_gv/lib/python3.7/site-packages/conda_build/environ.py", line 867, in create_env
    execute_actions(actions, index)
  File "/home/zjduan/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/forge_gv/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/zjduan/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/forge_gv/lib/python3.7/site-packages/conda/plan.py", line 321, in execute_actions
    execute_instructions(plan, index, verbose)
  File "/home/zjduan/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/forge_gv/lib/python3.7/site-packages/conda/plan.py", line 533, in execute_instructions
    cmd(state, arg)
  File "/home/zjduan/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/forge_gv/lib/python3.7/site-packages/conda/instructions.py", line 73, in UNLINKLINKTRANSACTION_CMD
    unlink_link_transaction.execute()
  File "/home/zjduan/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/forge_gv/lib/python3.7/site-packages/conda/core/link.py", line 247, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "/home/zjduan/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/forge_gv/lib/python3.7/site-packages/conda/core/link.py", line 712, in _execute
    rollback_excs,
conda.CondaMultiError: post-link script failed for package conda-forge::cudatoolkit-dev-10.0-2
location of failed script: /home/zjduan/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/forge_gv/conda-bld/graphvite_1566605285809/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/.cudatoolkit-dev-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout:
stderr: Traceback (most recent call last):
  File "/home/zjduan/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/forge_gv/conda-bld/graphvite_1566605285809/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/cudatoolkit-dev-post-install.py", line 44, in <module>
    from conda.exports import download, hashsum_file
ModuleNotFoundError: No module named 'conda'

return code: 1
```

According to the information, I then tried to add `conda` on build/host, but I still get the following error information
```
export PREFIX=/home/conda/feedstock_root/build_artifacts/graphvite_1566609493449/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
export BUILD_PREFIX=/home/conda/feedstock_root/build_artifacts/graphvite_1566609493449/_build_env
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/graphvite_1566609493449/work
ln: target `/home/conda/feedstock_root/build_artifacts/graphvite_1566609493449/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/zstdmt' is not a directory
Traceback (most recent call last):
  File "/home/conda/.ci_support/build_all.py", line 131, in <module>
    build_all(args.recipes_dir, args.arch)
  File "/home/conda/.ci_support/build_all.py", line 68, in build_all
    build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
  File "/home/conda/.ci_support/build_all.py", line 121, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2343, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1491, in build
    cwd=src_dir, stats=build_stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 397, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 377, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/conda/feedstock_root/build_artifacts/graphvite_1566609493449/work/conda_build.sh']' returned non-zero exit status 1.
```

It seems that there are some problems about using `cudatoolkit-dev`, and I am not able to figure it out.

**Comment by h-vetinari** [comment]
Hey @zjduan

Are you behind a firewall? `cudatoolkit-dev` will fail if it cannot download the CUDA drivers. There are [some environment variables](https://github.com/conda-forge/cudatoolkit-dev-feedstock/pull/11) to get around this if necessary, but in general, I would recommend to post your recipe (even if WIP) to https://www.github.com/conda-forge/staged-recipes, because there more people will be able to provide feedback to any problems you might encounter.

**Comment by h-vetinari** [comment]
Just letting people subscribed to this issue know that https://github.com/conda-forge/staged-recipes/pull/16943 is nearing completion.

**Comment by h-vetinari** [comment]
Closing this as builds are now being published in conda-forge through https://github.com/conda-forge/graphvite-feedstock for a while.

Try it with
```
conda install -c conda-forge graphvite  # or graphvite-mini
```
